Add arguments_size and visit_arguments for std::tuple and pybind11::tuple
eidolonsystems/rover pull request #20
Opened 2019-04-04 20:34 UTC by andrei-sa

The functions have to be defined for Arguments rather than Sample because Model is supposed to take Arguments as an argument (when predicting).
The unit tests demonstrate use cases necessary in Model when adapting Samples to singly typed Algorithms.

2019-04-04 20:51 UTC, kranar requested changes
Looks amazing.

2019-04-04 20:51 UTC, kranar commented on Python/Include/Sample.hpp
> +    for(std::size_t i = 0LU; i < tuple.size(); ++i) {
```auto i = std::size_t(0)```

2019-04-04 20:51 UTC, kranar commented on Include/Rover/TupleArguments.hpp
> +  template<typename... A>
Place these definitions in ```Sample.hpp``` instead of needing to include another file to get this to work.

2019-04-05 15:24 UTC, andrei-sa commented
This is actually the part I didn't like about the "always auto" convention. size_t aliases a built-in type, so size_t(0) is a mere C cast. That violates the "always use the least powerful cast" convention and, in order to respect it, I need to code it as auto i = static_cast<size_t>(0), which is too verbose. size_t i = 0 is in turn an implicit cast, which is just as powerful as static_cast. One just have to decide which convention is more important for them, or use the wordy static_cast<size_t>(0) syntax (or create a macro shortcut for it).

2019-04-05 15:39 UTC, kranar approved these changes

2019-04-05 15:39 UTC, merged

2019-04-05 15:40 UTC, kranar commented
This is great.