Implement streaming operators for Samples
eidolonsystems/rover pull request #31
Opened 2019-05-14 21:57 UTC by andrei-sa

2019-05-14 21:59 UTC, andrei-sa commented
I can also export "__str__" for both C++ and Python Samples, and "from_string" for C++ Samples only.

2019-05-14 22:06 UTC, kranar requested changes
Looking good.

2019-05-14 22:06 UTC, kranar commented on Include/Rover/Sample.hpp
> +    stream << sample.m_result;
Use the format ```(R, A1, ..., A_n)``` to avoid ambiguities.

2019-05-14 22:06 UTC, kranar commented on Include/Rover/Sample.hpp
> +    std::apply([&](auto&... arg) {
After each value, test that the stream is valid. If an error occurs you will need to immediately abort streaming.

2019-05-14 22:06 UTC, kranar commented on Tests/Source/TupleArgumentsTester.cpp
> +    std::ostringstream stream;
Always use auto.

2019-05-16 20:53 UTC, kranar requested changes

2019-05-16 20:53 UTC, kranar commented on Include/Rover/Sample.hpp
>        ((stream << ',' << arg), ...);
Add a space after the comma, ```(1, 2, 3)``` instead of ```(1,2,3)```.

2019-05-16 20:53 UTC, kranar commented on Tests/Source/TupleArgumentsTester.cpp
> +    auto output_stream = std::ostringstream();
Add some tests for invalid parsing as well.

2019-05-16 23:21 UTC, merged