Support categorical elements in Basis
eidolonsystems/rover pull request #40
Opened 2019-06-07 22:56 UTC by andrei-sa

Had to use the real dummy encoding (without the extra dimension for outliers) because otherwise it is impossible to make the model well-defined during learning. Outliers are handled by setting each dimension equal to `1.0 / num_categories`.
Tests for categorical linear regression are available in `LinearRegressionModelTester.cpp`.

2019-06-07 22:59 UTC, andrei-sa commented on Include/Rover/Basis.hpp
> +                    result.push_back(static_cast<ScalarType>(1.));
Can as well use `emplace_back`, but it won't be conventional where `ScalarType` is already `double`.

2019-06-10 14:13 UTC, kranar requested changes

2019-06-10 14:13 UTC, kranar commented on Include/Rover/Basis.hpp
> +      explicit BasisArguments(ArgumentsFwd&& args);
Is this supposed to be variadic?

2019-06-10 14:13 UTC, kranar commented on Python/Include/Basis.hpp
> +
No need for the blank line on 17.

2019-06-10 15:38 UTC, kranar approved these changes

2019-06-10 15:38 UTC, merged